server:
  port: 81

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/shop
    username: sbsst
    password: sbs123414
  security:
    user:
      name: admin
      password: password
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDB53Dialect


logging.level:
  #org.hibernate.SQL: debug
  org.hibernate.type: trace
